//! Pane launch: tmux hosts the process, withdone decides when it is finished.
//!
//! `SPEC-001-circus-agent-harness#CON-002`. The shape below is dictated by
//! three facts about the tools Circus composes, each verified rather than
//! assumed:
//!
//! 1. **A tmux pane is forked by the tmux server, not by its caller.** The
//!    pane is never a child of the Circus process, so completion cannot be
//!    learned by waiting on a child. It is learned from a status file the pane
//!    writes.
//! 2. **withdone unlinks the sentinel on both exit paths.** Its exit code is
//!    the sentinel value when the worker wrote one, and the child's own code
//!    otherwise, and after the fact the two are indistinguishable. A wrapper
//!    script therefore records the child's own exit; its *absence* is what
//!    identifies the sentinel path, because withdone terminates the group
//!    before the wrapper can write.
//! 3. **withdone refuses a sentinel that already exists.** Circus mints a
//!    fresh path per attempt and never reuses one.
//!
//! Driver argv is passed through tmux's own argument vector into `"$@"`. It is
//! never concatenated into script text. Only Circus's own paths are embedded,
//! and those go through [`crate::core::shquote`].

use std::fs;
use std::path::Path;
use std::thread::sleep;
use std::time::{Duration, Instant};

use super::proc::{self, Invoker};
use super::ui::{self, Ui};
use super::{Error, Result};
use crate::core::paths::AttemptPaths;
use crate::core::record::CompletionMethod;
use crate::core::shquote::quote_path;

/// SIGTERM-to-SIGKILL grace given to withdone, in seconds. Sits inside the
/// 10 s deadline of `#NFR-002` with room for Circus to observe the result.
const GRACE_SECONDS: u32 = 5;

/// The cleanup deadline of `#NFR-002`, as a `param` of its temporal property.
pub const CLEANUP_DEADLINE: Duration = Duration::from_secs(10);

/// How often to look for the pane's status file.
const POLL: Duration = Duration::from_millis(100);

/// When the first progress line appears. Early, because clig.dev's point about
/// showing feedback quickly matters most when the operator cannot yet tell
/// whether anything started.
const FIRST_PROGRESS: Duration = Duration::from_secs(2);

/// How often progress repeats on a terminal, where the line is rewritten in
/// place and costs nothing.
const PROGRESS_TTY: Duration = Duration::from_secs(1);

/// How often progress repeats elsewhere, where each report is a new line in
/// someone's log. `#REQ-008.d` requires at least once every 60 s.
const PROGRESS_PLAIN: Duration = Duration::from_secs(30);

/// What a completed launch produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LaunchOutcome {
    pub pane_name: String,
    /// withdone's exit code: the sentinel value, or the child's code.
    pub transport_exit_code: i32,
    /// The value the worker wrote, when it wrote one.
    pub sentinel_value: Option<i32>,
    pub completion_method: CompletionMethod,
    /// Live processes left in the pane's group at the deadline — `#OBS-003`.
    pub process_group_residue: u32,
}

/// Start the attempt in a named tmux pane and block until it finishes.
pub fn launch(
    inv: &mut Invoker,
    paths: &AttemptPaths,
    driver: &str,
    args: &[String],
    env: &[(String, String)],
    ui: Ui,
) -> Result<LaunchOutcome> {
    // Resolve every external program up front, so an absent tool exits 127
    // before anything starts — `#CON-006`, `#TEST-013`.
    inv.resolve("tmux")?;
    let withdone = inv.resolve("withdone")?;
    let driver_path = inv.resolve(driver)?;

    let go = paths.attempt_dir.join("go");
    let marker = paths.attempt_dir.join("child-exit");
    let runner = paths.attempt_dir.join("runner.sh");
    let wrapper = paths.attempt_dir.join("wrapper.sh");

    // A relaunch would find these from the previous run. `#CON-002` refuses a
    // relaunch, so reaching here with them present means a half-finished
    // attempt; clear the transient ones and leave the durable ones alone.
    for p in [&go, &marker, &paths.status] {
        let _ = fs::remove_file(p);
    }
    if paths.sentinel.exists() {
        return Err(Error::usage(format!(
            "the sentinel {} already exists; withdone requires a fresh path",
            paths.sentinel.display()
        )));
    }

    write_script(
        &wrapper,
        &format!(
            "#!/bin/sh\n\
             # generated by circus — records the child's own exit code\n\
             \"$@\"\n\
             code=$?\n\
             printf '%s' \"$code\" > {tmp} && mv {tmp} {marker}\n\
             exit \"$code\"\n",
            tmp = quote_path(&marker.with_extension("tmp")),
            marker = quote_path(&marker),
        ),
    )?;

    write_script(
        &runner,
        &format!(
            "#!/bin/sh\n\
             # generated by circus — waits for the log pipe, then runs the driver\n\
             while [ ! -f {go} ]; do sleep 0.05; done\n\
             {withdone} -s {sentinel} --grace {grace} -- {wrapper} \"$@\"\n\
             code=$?\n\
             printf '%s' \"$code\" > {tmp} && mv {tmp} {status}\n",
            go = quote_path(&go),
            withdone = quote_path(&withdone),
            sentinel = quote_path(&paths.sentinel),
            grace = GRACE_SECONDS,
            wrapper = quote_path(&wrapper),
            tmp = quote_path(&paths.status.with_extension("tmp")),
            status = quote_path(&paths.status),
        ),
    )?;

    // tmux argv, not a shell string: the driver and its arguments cross as
    // separate words and are never parsed by anything.
    // `new-session`, not `new-window`: `new-window` needs a server that is
    // already running and puts the pane in whatever session the operator
    // happens to be using. A detached session of its own starts the server
    // when there is none, stays out of the operator's layout, and is
    // attachable by the name `#REQ-002.b` fixes — `tmux attach -t <pane>`.
    let mut argv: Vec<String> = vec![
        "new-session".into(),
        "-d".into(),
        "-P".into(),
        "-F".into(),
        "#{pane_id} #{pane_pid}".into(),
        "-s".into(),
        paths.pane_name.clone(),
        "-n".into(),
        paths.pane_name.clone(),
        "-c".into(),
        paths.worktree.to_string_lossy().into_owned(),
    ];
    for (k, v) in env {
        argv.push("-e".into());
        argv.push(format!("{k}={v}"));
    }
    argv.extend([
        "--".into(),
        "/bin/sh".into(),
        runner.to_string_lossy().into_owned(),
        driver_path.to_string_lossy().into_owned(),
    ]);
    argv.extend(args.iter().cloned());

    let created = inv.run_ok("tmux", &argv)?;
    let (pane_id, pane_pid) = created
        .split_once(' ')
        .ok_or_else(|| Error::software(format!("tmux reported an unreadable pane: {created:?}")))?;
    let pane_pid: i32 = pane_pid.trim().parse().map_err(|_| {
        Error::software(format!(
            "tmux reported an unreadable pane pid: {pane_pid:?}"
        ))
    })?;
    let pgid = proc::process_group_of(inv, pane_pid).unwrap_or(pane_pid);

    // Copy the pane's output to the attempt log — `#REQ-002.c`. Both streams
    // reach the pane's terminal, so both reach the log.
    inv.run_ok(
        "tmux",
        &[
            "pipe-pane".to_string(),
            "-t".to_string(),
            pane_id.to_string(),
            "-o".to_string(),
            format!("cat >> {}", quote_path(&paths.log)),
        ],
    )?;

    // Release the runner only once the pipe is attached, so no output written
    // before the pipe existed is lost.
    fs::write(&go, b"")?;

    // `#REQ-008.c` — before the wait, not after it. An operator who
    // interrupts needs this command at that moment.
    ui.state(&format!("{} is running", paths.pane_name));
    ui.emphasis(&format!("watch it:  tmux attach -t {}", paths.pane_name));
    ui.hint(&format!("transcript: {}", paths.log.display()));

    let transport_exit_code = wait_for_status(&paths.status, pane_id, inv, ui)?;
    ui.end_progress();

    // Cleanup is withdone's job; Circus measures whether it worked.
    //
    // In practice there are two reapers, not one: tmux also sends SIGHUP to
    // the pane's process group when the pane dies. Residue therefore means a
    // process that ignored both withdone's SIGTERM/SIGKILL and tmux's SIGHUP,
    // which is rare and worth failing the attempt over.
    let deadline = Instant::now() + CLEANUP_DEADLINE;
    let mut residue = proc::process_group_residue(inv, pgid);
    while residue > 0 && Instant::now() < deadline {
        sleep(POLL);
        residue = proc::process_group_residue(inv, pgid);
    }

    // The marker exists only if the child returned on its own. withdone kills
    // the group the moment the sentinel is written, so on that path the
    // wrapper never reaches its final line.
    let (completion_method, sentinel_value) = match fs::read_to_string(&marker) {
        Ok(_) => (CompletionMethod::ChildExit, None),
        Err(_) => (CompletionMethod::Sentinel, Some(transport_exit_code)),
    };

    Ok(LaunchOutcome {
        pane_name: paths.pane_name.clone(),
        transport_exit_code,
        sentinel_value,
        completion_method,
        process_group_residue: residue,
    })
}

fn write_script(path: &Path, body: &str) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::write(path, body)?;
    fs::set_permissions(path, fs::Permissions::from_mode(0o755))?;
    Ok(())
}

/// Block until the pane records a status, or until the pane is gone.
///
/// A pane that dies without writing a status crashed or was killed from
/// outside. That is a transport outcome like any other, and it is reported as
/// such rather than hanging.
fn wait_for_status(status: &Path, pane_id: &str, inv: &mut Invoker, ui: Ui) -> Result<i32> {
    let started = Instant::now();
    let mut next_report = started + FIRST_PROGRESS;
    let every = if ui.is_terminal() {
        PROGRESS_TTY
    } else {
        PROGRESS_PLAIN
    };

    loop {
        if let Some(code) = read_status(status) {
            return Ok(code);
        }
        if !pane_alive(inv, pane_id) {
            // Give a status written just as the pane closed one last chance.
            sleep(POLL);
            return read_status(status).ok_or_else(|| {
                Error::software("the tmux pane closed without recording an outcome")
            });
        }
        let now = Instant::now();
        if now >= next_report {
            ui.progress(&format!(
                "running for {}",
                ui::human_duration(now.duration_since(started))
            ));
            next_report = now + every;
        }
        sleep(POLL);
    }
}

fn read_status(status: &Path) -> Option<i32> {
    fs::read_to_string(status).ok()?.trim().parse().ok()
}

fn pane_alive(inv: &mut Invoker, pane_id: &str) -> bool {
    inv.run("tmux", &["list-panes", "-a", "-F", "#{pane_id}"])
        .map(|o| {
            String::from_utf8_lossy(&o.stdout)
                .lines()
                .any(|l| l.trim() == pane_id)
        })
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_cleanup_deadline_matches_the_specified_bound() {
        // NFR-002's param is 10s. A change here is a change to a control.
        assert_eq!(CLEANUP_DEADLINE, Duration::from_secs(10));
        assert!(
            u64::from(GRACE_SECONDS) < CLEANUP_DEADLINE.as_secs(),
            "withdone's grace must fit inside the deadline Circus measures"
        );
    }
}
